### ISSUE TITLE
Calendar view improvements

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#100]
Some minor tweaks to the calendar view:
- [x] Hide weeks of current month which have passed
- [x] Consolidate last week of a month with the first week of the next month in a single row
- [x] Color background (same scheme as in normal view)
- [x] Highlight events user has registered for
- [x] Fit whole week on mobile (hide times, cut off text, remove padding, etc.)
- [x] Equal width columns
- [x] Min-height rows, e.g. 30em

**Comment by heddendorp** [comment]
I think the first two suggestions are in now 👍
