### ISSUE TITLE
Event categories

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#102]
Sort events into categories, e.g. Sports, Culture, City Trips, and color them accordingly

**Comment by heddendorp** [comment]
While I would love to categorize event templates (and with that probably events as well) I don't think it's worth exposing this with colours to users in the event list. Having a legend to interpret event colours seems to me like introducing more complexity.
However, i think it would greatly improve the event template page and make it easier to navigate and filters could be exposed to users in the event list to help them get an overview.
Also the category can be part of the event details for sure.
