### ISSUE TITLE
Calendar integration broken

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#111]
Multiple users report that calendar integration is broken

**Comment by heddendorp** [comment]
It seems like the cdn config was off and did not properly forward the calendar requests to the server.
It should recover soon. The public calendar shows it's working https://larrybolt.github.io/online-ics-feed-viewer/#feed=https%3A//tumi.esn.world/cal/public&cors=false&title=My%20Feed&hideinput=false
