### ISSUE TITLE
Sticky footer on the bottom when loading

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#114]
Sticky the footer on the bottom when the page is loading, looks weird. Alternate approach: make page always take up remaining space

**Comment by heddendorp** [comment]
it's surprisingly hard to achieve this as the scroll restoration is broken if the html and body are set to `min-height: 100%`. While I agree that it would look much better it seemed to me like a necessary downside of restoring the scroll position.
Happy to have this fixed, just mentioning to prevent regressions

**Comment by jacbz** [comment]
Redundant with the design overhaul
