### ISSUE TITLE
Issue with routing when user is logged in

### ISSUE THREAD

**Issue by euberdeveloper** [heddendorp/tumi#133]
If the user is not logged in (i.e. by opening an incognito tab), going to the url of the kind `https://tumi.esn.world/events/{event_id}` just works.

If the user is  logged in, instead, the page will be redirected to `https://tumi.esn.world/profile/new`.

This happens only if the url is the first to be present in the url bar, so in the initial routing of Angular.

**Comment by heddendorp** [comment]
Could you verify that all I fo on that page is filled in?
Especially the enrollment status should not be _none_.

**Comment by euberdeveloper** [comment]
👍
