### ISSUE TITLE
Revoking registration codes

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#162]
- Users should be able to revoke a created registration code, if nobody has used it yet
- Admins should be able to revoke any registration code

**Comment by Imagination-Factory** [comment]
Hi Jacob, a few questions about this enhancement feature:

Should the behavior be the same for both either the user revokes his/her own registration code or an admin performs this action?
For clarification: in both scenarios the user should still be registered for this event and no refund should be paid?

Frontend part: where do you as an admin want to be able to revoke registration codes? In the current events tab with registered participants and/or in the section of  all "Registration Codes" currently available on the platform?

Thanks,
Christian

**Comment by jacbz** [comment]
The behavior should be the same.

Revoking should be possible where admins currently create the registration codes - in the event management panel.

**Comment by jacbz** [comment]
Closed by 35851cb6f0ea0a721b00d58238de499b66368137
