### ISSUE TITLE
Visual bug on the day overview when scrollable

### ISSUE THREAD

**Issue by heddendorp** [heddendorp/tumi#217]
If the day overview of the calendar is scrolling, there is a glitch that makes one border disappear.
![image](https://user-images.githubusercontent.com/3612748/175977022-570d07ee-90ce-43ad-a915-015fa1f1b1c0.png)

**Comment by jacbz** [comment]
Not only in the calendar:

![image](https://user-images.githubusercontent.com/4510930/176134343-4a3e90d8-88ca-4ec2-ac51-0161d15a5398.png)

**Comment by jacbz** [comment]
This should be fixed with the design overhaul
