### ISSUE TITLE
Add link to Telegram group in footer

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#248]
In front of the Instagram button

**Comment by AdwaitKulkarni58** [comment]
Hi,

I would like to tackle this issue. Can you provide me with the link to the group and assign me to this issue?

Thanks

**Comment by heddendorp** [comment]
@AdwaitKulkarni58 Thanks for the interest, feel free to reach out if you run in to any trouble
The telegram link is https://t.me/+PtNU9JqOE19lZjMy
`icon-telegram-app` is already available and can be used for this
