### ISSUE TITLE
Tutor Hub

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#271]
Replace the "Tutor Guide" link with a new, dedicated Tutor Hub.

The Tutor Hub should display:
- a list of board members with their tasks, and buttons linking their Slack and WhatsApp, so tutors know who to contact
- list of TUMi Teams, team chefs, and upcoming events from each team
- a list of active tutors (active defined as >0 events in the current semester), sorted by number of created/organized events (sort of a "leaderboard") -- including a link to a "all time leaderboard"
- some stats, e.g. number of events this semester (past, future, etc.)
- optional: a "birthday hub" displaying which (active) tutors are celebrating their birthday today
- a link to WhatsApp, Slack
- a link to resources, e.g. tutor guide, Satzung, "how to rent a bus", etc.
  - tutor guide should be a native page on the app

Goal: make TUMi feel more closely connected.

**Comment by heddendorp** [comment]
This is a really cool idea, it would be great if you could follow it up with a data model that allows saving the info without hardcoding it for TUMi @jacbz
