### ISSUE TITLE
Time zone always to CET

### ISSUE THREAD

**Issue by jacbz** [heddendorp/tumi#373]
All times displayed by the client and processed by the server should be German time.

Otherwise some people will get this mess:
![image](https://user-images.githubusercontent.com/4510930/185803027-00309572-b2e7-415f-934e-ec1267d26835.png)

**Comment by heddendorp** [comment]
Haha oh no, we actually hat confusion before while having online events with people from other timezones.
We should find a way to change this for the entire application. We should probably also look into the correct way of using the localize service to make sure the formatting is also german 👍

**Comment by jacbz** [comment]
It makes no sense to display times of non-online events (which are 99% of the events) in the local timezone. The correct approach is to display all dates in the German time zone and take extra care when writing the description for online events. This is in line with other websites, such as TUMonline, government websites etc.

Another approach could be to extend the date pipe so that it recognizes the current timezone and adds a "CET"/"CEST" after the date, if the user is not in the time zone.

As of now, the calendar is completely unusable for all users not in Europe. Since many won't be in Europe at the end of September, when signups open, this is a usability issue of the highest degree.

**Comment by heddendorp** [comment]
100% agreed, even with online events, users where assuming the time is german and showed up late. It would be good to have consistency here.
